{{- if .Values.variables.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dental-clinic-management-system.fullname" . }}
  labels:
    {{- include "dental-clinic-management-system.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.variables.configmap | nindent 2}}
{{- end }}