/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Treatment } from "./Treatment";
import { TreatmentCountArgs } from "./TreatmentCountArgs";
import { TreatmentFindManyArgs } from "./TreatmentFindManyArgs";
import { TreatmentFindUniqueArgs } from "./TreatmentFindUniqueArgs";
import { CreateTreatmentArgs } from "./CreateTreatmentArgs";
import { UpdateTreatmentArgs } from "./UpdateTreatmentArgs";
import { DeleteTreatmentArgs } from "./DeleteTreatmentArgs";
import { TreatmentService } from "../treatment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Treatment)
export class TreatmentResolverBase {
  constructor(
    protected readonly service: TreatmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "read",
    possession: "any",
  })
  async _treatmentsMeta(
    @graphql.Args() args: TreatmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Treatment])
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "read",
    possession: "any",
  })
  async treatments(
    @graphql.Args() args: TreatmentFindManyArgs
  ): Promise<Treatment[]> {
    return this.service.treatments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Treatment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "read",
    possession: "own",
  })
  async treatment(
    @graphql.Args() args: TreatmentFindUniqueArgs
  ): Promise<Treatment | null> {
    const result = await this.service.treatment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Treatment)
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "create",
    possession: "any",
  })
  async createTreatment(
    @graphql.Args() args: CreateTreatmentArgs
  ): Promise<Treatment> {
    return await this.service.createTreatment({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Treatment)
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "update",
    possession: "any",
  })
  async updateTreatment(
    @graphql.Args() args: UpdateTreatmentArgs
  ): Promise<Treatment | null> {
    try {
      return await this.service.updateTreatment({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Treatment)
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "delete",
    possession: "any",
  })
  async deleteTreatment(
    @graphql.Args() args: DeleteTreatmentArgs
  ): Promise<Treatment | null> {
    try {
      return await this.service.deleteTreatment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
